services:
  nowted-frontend-dev:
    image: nowted-frontend-dev
    container_name: nowted-frontend-dev
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend/:/usr/src/app
    environment:
      - REACT_APP_BACKEND_URL=/api

  postgres_db:
    image: postgres
    container_name: postgres-dev
    environment:
      POSTGRES_DB: development
      POSTGRES_PASSWORD: secret

  redis_db:
    image: redis
    container_name: redis-dev
    tty: true
    command: ["redis-server", "--appendonly", "yes"]

  nginx-dev:
    image: nginx-dev
    build:
      context: ./nginx
      dockerfile: dev.Dockerfile
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - nowted-frontend-dev

  nowted-backend-dev:
    image: nowted-backend-dev
    container_name: nowted-backend-dev
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend/:/usr/src/app
    environment:
      DATABASE_URL: postgres://postgres:secret@postgres-dev:5432/development
      REDIS_URL: redis://redis-dev:6379
      NODE_ENV: development
    depends_on:
      - postgres_db
      - redis_db
