version: '3.8'

services:
  server:
    image: backend-image
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:secret@db:5432/postgres
    volumes:
      - ./:/usr/src/app
    ports:
      - 3001:3001
    container_name: backend-dev

  db: 
    image: postgres
    container_name: postgres
    # restart: always
    environment:
      POSTGRES_PASSWORD: secret
      # PGDATA: /var/lib/postgresql/data/pgdata
    # volumes:
      # - /volumes/postgres:/var/lib/postgresql/data 
    ports:
      - 5432:5432