version: '3.8'

services:
  postgres_db:
    image: postgres
    container_name: postgres-dev
    # restart: always
    environment:
      POSTGRES_DB: development
      POSTGRES_PASSWORD: secret
      # PGDATA: /var/lib/postgresql/data/pgdata
    # volumes:
    # - /volumes/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis_db:
    image: redis
    container_name: redis-dev
    ports:
      - 6379:6379
    tty: true
    command: ['redis-server', '--appendonly', 'yes'] # Overwrite the CMD
    # volumes: # Declare the volume
    #   - ./redis_data:/data

  server:
    image: nowted-backend-image
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:secret@postgres-dev:5432/development
      REDIS_URL: redis://redis-dev:6379
      NODE_ENV: development
    volumes:
      - ./:/usr/src/app
    ports:
      - 3001:3001
    container_name: backend-dev
    depends_on:
      - postgres_db
      - redis_db
