version: '3.8'

services:
  postgres_db:
    image: postgres
    container_name: postgres-dev
    restart: always
    environment:
      POSTGRES_DB: development
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432

  redis_db:
    image: redis
    container_name: redis-dev
    ports:
      - 6379:6379
    tty: true
    command: ['redis-server', '--appendonly', 'yes'] # Overwrite the CMD

  server:
    image: nowted-backend-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:secret@postgres-dev:5432/development
      REDIS_URL: redis://redis-dev:6379
      NODE_ENV: development
      PGUSER: 'postgres'

    ports:
      - 3001:3001
    container_name: backend-dev
    depends_on:
      - postgres_db
      - redis_db
