POST http://localhost:8080/api/users
Content-Type: application/json

{
    "username": "digran",
    "email": "digran@gmail.com",
    "password": "12345678"
}

###
POST http://localhost:8080/api/testing/reset