name: Build, Versioning, & Push Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [synchronize]

jobs:
  build_push_image:
    name: Build & push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Build Nowted Frontend Image
        run: docker build ./frontend -t danggro/nowted-frontend:latest

      - name: Build Nowted Backend Image
        run: docker build ./backend -t danggro/nowted-backend:latest

      - name: Build Nowted Nginx Image
        run: docker build ./nginx -t danggro/nowted-nginx:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Nowted Frontend Image
        run: docker push danggro/nowted-frontend:latest

      - name: Push Nowted Backend Image
        run: docker push danggro/nowted-backend:latest

      - name: Push Nowted Nginx Image
        run: docker push danggro/nowted-nginx:latest

  versioning:
    name: Add tag github
    runs-on: ubuntu-latest
    needs: build_push_image
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          CUSTOM_TAG: v0.0.0
          DEFAULT_BUMP: "#patch"
          REPO_OWNER: danggro
